# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

# We already have a default network using the bridge adapter, so we don't need to redefine it.

services:
  master_1:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.MetadataServer -h master1.logservice.ratis.org -p 9999 -d /tmp/logservice-metadata -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
     - 9999
    networks:
      default:
        aliases:
          - master1.logservice.ratis.org
  master_2:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.MetadataServer -h master2.logservice.ratis.org -p 9999 -d /tmp/logservice-metadata -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
     - 9999
    networks:
      default:
        aliases:
          - master2.logservice.ratis.org
  master_3:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.MetadataServer -h master3.logservice.ratis.org -p 9999 -d /tmp/logservice-metadata -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
     - 9999
    networks:
      default:
        aliases:
          - master3.logservice.ratis.org
  worker_1:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.LogServer -p 9999 -h worker1.logservice.ratis.org -d /tmp/logservice-worker -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
      - 9999
    networks:
      default:
        aliases:
          - worker1.logservice.ratis.org
  worker_2:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.LogServer -p 9999 -h worker2.logservice.ratis.org -d /tmp/logservice-worker -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
      - 9999
    networks:
      default:
        aliases:
          - worker2.logservice.ratis.org
  worker_3:
    image: ratis-logservice:latest
    command: "java -cp 'conf:lib/*' org.apache.ratis.logservice.server.LogServer -p 9999 -h worker3.logservice.ratis.org -d /tmp/logservice-worker -q master1.logservice.ratis.org:9999,master2.logservice.ratis.org:9999,master3.logservice.ratis.org:9999"
    ports:
      - 9999
    networks:
      default:
        aliases:
          - worker3.logservice.ratis.org
  graphite:
    image: graphiteapp/graphite-statsd 
    ports:
      - 8000:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125
      - 8126:8126
    networks:
      default:
        aliases:
          - graphite.logservice.ratis.org
